### ISSUE TITLE
Node error with all commands

### ISSUE THREAD

**Issue by dellow** [omgimanerd/doclt#8]
Hi,

After supplying my token, when I run any command I get this error:

    /usr/local/lib/node_modules/doclt/lib/Display.js:187
      return process.argv.includes('--json');
                          ^

    TypeError: process.argv.includes is not a function
        at json (/usr/local/lib/node_modules/doclt/lib/Display.js:187:23)
        at Object.exports.displayAccount.exports.displayAction.exports.displayActionID.exports.displayActions.exports.displayDomain.exports.displayDomains.exports.displayDomainRecord.exports.displayDomainRecords.exports.displayDroplet.table.push.apply.exports.displayDroplets.table.push.apply.droplets.map [as displayDroplets] (/usr/local/lib/node_modules/doclt/lib/Display.js:447:7)
        at /usr/local/lib/node_modules/doclt/commands/droplets/list.js:23:13
        at null._onTimeout (/usr/local/lib/node_modules/doclt/node_modules/digitalocean/lib/digitalocean/client.js:198:15)
        at Timer.listOnTimeout (timers.js:92:15)

**Comment by omgimanerd** [comment]
Hi there, what version of node are you running?

**Comment by omgimanerd** [comment]
![image](https://cloud.githubusercontent.com/assets/7121024/22658463/275b5414-ec68-11e6-9ea1-49ba2fbbb7d1.png)
I suspect the error has to do your version of node not supporting `Array.prototype.includes()`

**Comment by omgimanerd** [comment]
@sdellow I may need to rewrite some stuff to expand support for previous versions of node.

**Comment by dellow** [comment]
Yea I ran this at home with 6.9.5 and it worked fine.

Running 4.4.2 on the machine the commands failed.

**Comment by omgimanerd** [comment]
I just tested it on node `v4.4.2` with this bugfix and it worked.
I've bumped up doclt to version `1.1.4`
If you `npm install -g doclt`, it should work now.
